site_name: Dan Hayes CPD
nav:
  - Home: index.md
  - Structured Learning:
    - Overview: structured-learning/index.md
    - 2026-08-18 - HTB Academy Senior Web Penetration Tester path: structured-learning/2026-08-18-senior-web-pentester-path.md
  - Reflective Learning:
    - Overview: reflective-learning/index.md
    - 2026-08-19 - Create CPD Log: reflective-learning/2026-08-19-create-cpd-log.md
  - Professional Contribution:
    - Overview: professional-contribution/index.md
    - 2026-08-17 - Mentoring a Junior Colleague: professional-contribution/2026-08-17-mentoring-a-junior-colleague.md

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.code.copy

plugins:
  - search
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
